### ISSUE TITLE
2 phase commit with database and message broker

### ISSUE THREAD

**Issue by skazaruddin** [piomin/sample-spring-cloud-messaging#1]
@PostMapping
	public Order process(@RequestBody Order order) throws JsonProcessingException {
		Order o = repository.add(order); 
		LOGGER.info("Order saved: {}", mapper.writeValueAsString(order));
		boolean isSent = sender.send(o);
		LOGGER.info("Order sent: {}", mapper.writeValueAsString(Collections.singletonMap("isSent", isSent)));
		return o;
	}

In order controller, order is stored in ArrayList, but in production it will be either a SQL or NoSQL database. Moreover, persisting into database and publishing event into message broker in a single transaction is usage of 2-phase commit.Is not this evil thing, we are trying to avoid in microservice.

How will this transaction guarantee if I have a NoSQL datastore, as NoSQL doesn't support ACID.

Can you specify some better patterns to deal with above issues.

Code

**Comment by piomin** [comment]
You can use e.g. outbox pattern in that case
